### ISSUE TITLE
Is the plugin production ready?

### ISSUE THREAD

**Issue by michalkrajcovic** [burrunan/gradle-s3-build-cache#17]
Is the plugin production ready? Would it make sense to remove `Please note that this plugin is not yet ready for production. ` since version 1.x has already been published? And it seems that the plugin has active support and development? Stating that the plugin is not ready for production might discourage potential users of the plugin. 

Please consider removing `not yet ready for production` to gain wider adoption. Thanks

**Comment by vlsi** [comment]
Thank you for the heads-up
